export const CONTENTFUL_SLUGS = Object.freeze({
    PRIMARY_SITE_CONFIG: process.env.NEXT_PUBLIC_CONTENTFUL_SLUGS_PRIMARY_SITE_CONFIG as string,
    HEADER_SITE_NAVBAR: process.env.NEXT_PUBLIC_CONTENTFUL_SLUGS_HEADER_SITE_NAVBAR as string
});